// GENERATED FILE — do not hand-edit.
// Source of truth: shared/matching.js. Regenerate with:
//   node scripts/sync-shared.js  (or npm run dev / npm run build, which do it automatically)

/**
 * shared/matching.js
 *
 * Single source of truth for the ingredient-matching logic used by both
 * the backend (backend/server.js, via require) and the frontend's offline
 * fallback (frontend/src/matching.js, an ES-module copy of this file
 * generated by scripts/sync-shared.js). Previously this logic was
 * hand-duplicated in both places and had to be "kept in sync by hand" —
 * this file is now the only place it should ever be edited.
 *
 * Do not import Node- or browser-only APIs here; this file must run
 * unmodified in both a CommonJS backend and (via the sync script) an
 * ES-module frontend bundle.
 */

// Raw ingredient names in the dataset carry prep notes like "onion, diced"
// or "beans (optional)" — strip those down to a clean, display-friendly,
// deduplicated name.
export function cleanIngredientName(raw) {
  return raw
    .split(",")[0]
    .replace(/\([^)]*\)/g, "")
    .replace(/\s+/g, " ")
    .trim();
}

export function normalize(str) {
  return str.toLowerCase().trim().replace(/[^a-z0-9\s]/g, "").replace(/s$/, "");
}

// Dependency-free Levenshtein distance, used only for short-string typo
// tolerance (e.g. "chiken" -> "chicken"). Keeping this hand-rolled avoids
// pulling in a package for what's a small, well-understood algorithm.
export function levenshtein(a, b) {
  const m = a.length, n = b.length;
  if (m === 0) return n;
  if (n === 0) return m;
  let prev = new Array(n + 1);
  for (let j = 0; j <= n; j++) prev[j] = j;
  for (let i = 1; i <= m; i++) {
    const cur = [i];
    for (let j = 1; j <= n; j++) {
      cur[j] = a[i - 1] === b[j - 1]
        ? prev[j - 1]
        : 1 + Math.min(prev[j - 1], prev[j], cur[j - 1]);
    }
    prev = cur;
  }
  return prev[n];
}

export function fuzzyHit(u, target) {
  if (!target || u.length < 4 || target.length < 4) return false;
  const dist = levenshtein(u, target);
  return dist <= 1 || dist / Math.max(u.length, target.length) <= 0.25;
}

// Scores how well a single user-typed ingredient matches a single dish
// ingredient, from 0 (no match) to 1 (exact match), in tiers:
//   1.0  exact match on the ingredient's core name (prep notes stripped,
//        e.g. "onion" vs "onion, diced")
//   0.7  whole-word match against the ingredient's core or full name
//        (e.g. "onion" inside "green onion", "pickled onion", "onion powder" —
//        real hits, but weaker than having exactly that ingredient)
//   0.45 substring match that isn't a whole word
//   0.4  fuzzy match for likely typos (e.g. "chiken" -> "chicken")
//   0    no match
export function matchScore(userIngredient, dishIngredientRaw) {
  const u = normalize(userIngredient);
  if (!u) return 0;

  const core = normalize(cleanIngredientName(dishIngredientRaw));
  const full = normalize(dishIngredientRaw);
  if (!core && !full) return 0;

  if (u === core) return 1.0;

  const coreWords = core ? core.split(/\s+/).filter(Boolean) : [];
  const fullWords = full ? full.split(/\s+/).filter(Boolean) : [];
  if (coreWords.includes(u) || fullWords.includes(u)) return 0.7;

  if ((core && (core.includes(u) || u.includes(core))) || (full && (full.includes(u) || u.includes(full)))) {
    return 0.45;
  }

  if (fuzzyHit(u, core) || fuzzyHit(u, full)) return 0.4;
  for (const w of coreWords.length ? coreWords : fullWords) {
    if (fuzzyHit(u, w)) return 0.4;
  }

  return 0;
}

export function ingredientMatches(userIngredient, dishIngredient) {
  return matchScore(userIngredient, dishIngredient) > 0;
}

// Scores a dish against the user's ingredient list. Ingredients earlier in
// a dish's list are weighted more heavily than later ones — the dataset
// consistently lists the core/protein ingredients first and garnishes or
// optional extras last, so this is a reasonable proxy for "core" vs
// "minor" without needing extra metadata. The final percent blends
// match-tier strength (a whole-word hit counts for less than an exact
// one) with that positional weighting, so missing a core ingredient hurts
// more than missing a garnish, and a fuzzy/partial hit counts for less
// than a clean match.
//
// dishIngredientNames: string[] (raw ingredient name strings for one dish)
// userIngredients: string[] (raw strings the user typed/added)
// returns { matched: string[], missing: string[], matchPercent: number }
export function scoreDish(dishIngredientNames, userIngredients) {
  const n = dishIngredientNames.length;
  const matched = [];
  const missing = [];
  let weightedScore = 0;
  let weightedTotal = 0;

  dishIngredientNames.forEach((ing, idx) => {
    const weight = n - idx; // earlier ingredients weigh more
    weightedTotal += weight;
    let best = 0;
    for (const u of userIngredients) {
      const s = matchScore(u, ing);
      if (s > best) best = s;
      if (best === 1) break;
    }
    if (best > 0) {
      matched.push(ing);
      weightedScore += weight * best;
    } else {
      missing.push(ing);
    }
  });

  return {
    matched,
    missing,
    matchPercent: weightedTotal ? Math.round((weightedScore / weightedTotal) * 100) : 0,
  };
}
