#!/usr/bin/env node
/**
 * scripts/sync-shared.js
 *
 * Generates frontend/src/matching.js — an ES-module copy of
 * shared/matching.js — so the frontend's offline fallback and the
 * backend API use the exact same ingredient-matching logic from a
 * single source file (shared/matching.js). Never hand-edit
 * frontend/src/matching.js; it's regenerated by this script.
 *
 * Why not just `require()` the shared file directly from the frontend?
 * The frontend is bundled by Vite as native ES modules, and
 * shared/matching.js is plain CommonJS (so backend/server.js can
 * `require()` it with zero build step). Rather than add a bundler
 * plugin or a second module system, this script does one dumb, obvious
 * transform: strip the trailing `module.exports = {...}` block and
 * replace it with `export { ... }`, and prefix each top-level
 * `function` declaration with `export`. The function bodies are
 * copied verbatim.
 *
 * Usage: node scripts/sync-shared.js
 * This is wired up as a `predev` / `prebuild` step in frontend/package.json.
 */

const fs = require("fs");
const path = require("path");

const SHARED_PATH = path.join(__dirname, "..", "shared", "matching.js");
const FRONTEND_OUT_PATH = path.join(__dirname, "..", "frontend", "src", "matching.js");

function main() {
  const source = fs.readFileSync(SHARED_PATH, "utf8");

  const exportsMatch = source.match(/module\.exports\s*=\s*\{([\s\S]*?)\};?\s*$/);
  if (!exportsMatch) {
    throw new Error("sync-shared: couldn't find `module.exports = {...}` in shared/matching.js");
  }
  const exportedNames = exportsMatch[1]
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean);

  // Each top-level `function` declaration gets its own `export` prefix,
  // so no separate `export { ... }` block is needed (and wouldn't be safe
  // to add — it would duplicate these individual exports).
  const body = source.slice(0, exportsMatch.index).replace(/^function /gm, "export function ");

  const banner =
    "// GENERATED FILE — do not hand-edit.\n" +
    "// Source of truth: shared/matching.js. Regenerate with:\n" +
    "//   node scripts/sync-shared.js  (or npm run dev / npm run build, which do it automatically)\n\n";

  const output = banner + body.trim() + "\n";

  fs.writeFileSync(FRONTEND_OUT_PATH, output);
  console.log(`sync-shared: wrote ${path.relative(process.cwd(), FRONTEND_OUT_PATH)} (${exportedNames.length} exports)`);
}

main();
